# render.yaml
services:
  - type: web
    name: painel-previsao-vendas
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
